In [1]:
import torch

print("Torch Version :", torch.__version__)
print("CUDA Available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU :", torch.cuda.get_device_name(0))

Torch Version : 2.11.0+cu128
CUDA Available: True
GPU : Tesla T4


In [2]:
!git clone https://github.com/BhagyasRii/Advanced-AI-Medical-Intelligence-Platform.git

Cloning into 'Advanced-AI-Medical-Intelligence-Platform'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (59/59), done.
remote: Total 73 (delta 16), reused 65 (delta 8), pack-reused 0 (from 0)
Receiving objects: 100% (73/73), 14.29 KiB | 243.00 KiB/s, done.
Resolving deltas: 100% (16/16), done.


In [3]:
%cd Advanced-AI-Medical-Intelligence-Platform

/content/Advanced-AI-Medical-Intelligence-Platform


In [4]:
!ls

configs    ProjectProgress.md  requirements.txt  src	train.py
notebooks  README.md	       scripts		 tests


In [5]:
!find src -maxdepth 2 -type f

src/training/evaluator.py
src/training/optimizer.py
src/training/history.py
src/training/scheduler.py
src/training/__init__.py
src/training/engine.py
src/training/early_stopping.py
src/explainability/__init__.py
src/__init__.py
src/data/loaders.py
src/data/transforms.py
src/data/dataset.py
src/data/__init__.py
src/data/download.py
src/models/densenet121.py
src/models/metrics.py
src/models/losses.py
src/models/checkpoint.py
src/models/trainer.py
src/models/__init__.py
src/utils/logger.py
src/utils/seed.py
src/utils/__init__.py
src/utils/device.py


In [6]:
!pip install -r requirements.txt

In [7]:
from configs.config import cfg

print(cfg.DEVICE)

cuda


In [9]:
!python -m scripts.analyze_dataset

100% 194M/194M [00:02<00:00, 91.3MB/s]
Extracting files...

Dataset Location:
/root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1

Detected Splits:
  train      -> /root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1/chest-xray/train
  val        -> /root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1/chest-xray/val
  test       -> /root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1/chest-xray/test

TRAIN SET

Classes (6):
  Covid-19                  2417
  Emphysema                 2050
  Normal                    2671
  Pneumonia-Bacterial       2400
  Pneumonia-Viral           2413
  Tuberculosis              2600

Total Images : 14551
Most Common Image Size : (224, 224) (14551 images)
Corrupted Images : 0

VAL SET

Classes (6):
  Covid-19                  300
  Emphysema                 250
  Normal                    300
  Pneumonia-Bacterial       300


In [10]:
!pwd

/content/Advanced-AI-Medical-Intelligence-Platform


In [11]:
!python -m scripts.analyze_dataset


Dataset Location:
/root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1

Detected Splits:
  train      -> /root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1/chest-xray/train
  val        -> /root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1/chest-xray/val
  test       -> /root/.cache/kagglehub/datasets/mohamedasak/chest-x-ray-6-classes-dataset/versions/1/chest-xray/test

TRAIN SET

Classes (6):
  Covid-19                  2417
  Emphysema                 2050
  Normal                    2671
  Pneumonia-Bacterial       2400
  Pneumonia-Viral           2413
  Tuberculosis              2600

Total Images : 14551
Most Common Image Size : (224, 224) (14551 images)
Corrupted Images : 0

VAL SET

Classes (6):
  Covid-19                  300
  Emphysema                 250
  Normal                    300
  Pneumonia-Bacterial       300
  Pneumonia-Viral           300
  Tuberculosis             

In [13]:
!python -m scripts.train

Using Colab cache for faster access to the 'chest-x-ray-6-classes-dataset' dataset.
Epoch [1/30] Train Loss: 0.4369 Train Acc: 0.8327 Val Loss: 0.3460 Val Acc: 0.8644
Checkpoint saved: /content/Advanced-AI-Medical-Intelligence-Platform/outputs/checkpoints/best_model.pth
Epoch [2/30] Train Loss: 0.2638 Train Acc: 0.8945 Val Loss: 0.2829 Val Acc: 0.8862
Checkpoint saved: /content/Advanced-AI-Medical-Intelligence-Platform/outputs/checkpoints/best_model.pth
Epoch [3/30] Train Loss: 0.2167 Train Acc: 0.9142 Val Loss: 0.2512 Val Acc: 0.8999
Checkpoint saved: /content/Advanced-AI-Medical-Intelligence-Platform/outputs/checkpoints/best_model.pth
Epoch [4/30] Train Loss: 0.1884 Train Acc: 0.9262 Val Loss: 0.2368 Val Acc: 0.8993
Epoch [5/30] Train Loss: 0.1597 Train Acc: 0.9384 Val Loss: 0.2202 Val Acc: 0.9188
Checkpoint saved: /content/Advanced-AI-Medical-Intelligence-Platform/outputs/checkpoints/best_model.pth
Epoch [6/30] Train Loss: 0.1317 Train Acc: 0.9487 Val Loss: 0.2421 Val Acc: 0.9125
Ep

In [24]:
!python -m scripts.evaluate

Using Colab cache for faster access to the 'chest-x-ray-6-classes-dataset' dataset.
                     precision    recall  f1-score   support

           Covid-19       0.98      0.97      0.98       300
          Emphysema       0.97      0.98      0.97       250
             Normal       0.96      0.99      0.98       300
Pneumonia-Bacterial       0.95      0.88      0.91       300
    Pneumonia-Viral       0.90      0.94      0.92       300
       Tuberculosis       1.00      1.00      1.00       287

           accuracy                           0.96      1737
          macro avg       0.96      0.96      0.96      1737
       weighted avg       0.96      0.96      0.96      1737

[[292   8   0   0   0   0]
 [  5 245   0   0   0   0]
 [  0   0 297   1   2   0]
 [  0   0   6 264  30   0]
 [  0   0   6  13 281   0]
 [  0   0   0   0   0 287]]


In [26]:
!ls outputs/checkpoints

best_model.pth


In [18]:
from pathlib import Path

Path("outputs/checkpoints/best_model.pth").exists()

True

In [28]:
from google.colab import files

files.download("outputs/checkpoints/best_model.pth")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>